export const FETCH_GLOBAL_CONFIG = "FETCH_GLOBAL_CONFIG";
export const FETCH_GLOBAL_CONFIG_SUCCESS = "FETCH_GLOBAL_CONFIG_SUCCESS";
export const FETCH_GLOBAL_CONFIG_ERROR = "FETCH_GLOBAL_CONFIG_ERROR";
export const FETCH_GLOBAL_CONFIG_CANCEL = "FETCH_GLOBAL_CONFIG_CANCEL";
