export const OPEN_LIGHTBOX = "OPEN_LIGHTBOX";
export const CLOSE_LIGHTBOX = "CLOSE_LIGHTBOX";
export const SLIDE_INDEX_INCREMENT = "SLIDE_INDEX_INCREMENT";
export const SLIDE_INDEX_DECREMENT = "SLIDE_INDEX_DECREMENT";
